# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1660, 740)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.BrowsepushButton = QtWidgets.QPushButton(self.tab_3)
        self.BrowsepushButton.setGeometry(QtCore.QRect(20, 10, 93, 31))
        self.BrowsepushButton.setObjectName("BrowsepushButton")
        self.SettingsgroupBox = QtWidgets.QGroupBox(self.tab_3)
        self.SettingsgroupBox.setGeometry(QtCore.QRect(10, 420, 571, 261))
        self.SettingsgroupBox.setObjectName("SettingsgroupBox")
        self.Volumelabel = QtWidgets.QLabel(self.SettingsgroupBox)
        self.Volumelabel.setGeometry(QtCore.QRect(10, 20, 51, 21))
        self.Volumelabel.setObjectName("Volumelabel")
        self.PlayPausepushButton = QtWidgets.QPushButton(self.SettingsgroupBox)
        self.PlayPausepushButton.setGeometry(QtCore.QRect(320, 20, 93, 41))
        self.PlayPausepushButton.setObjectName("PlayPausepushButton")
        self.ShowSpectrogrampushButton = QtWidgets.QPushButton(self.SettingsgroupBox)
        self.ShowSpectrogrampushButton.setGeometry(QtCore.QRect(420, 20, 131, 41))
        self.ShowSpectrogrampushButton.setObjectName("ShowSpectrogrampushButton")
        self.VolumeverticalSlider = QtWidgets.QSlider(self.SettingsgroupBox)
        self.VolumeverticalSlider.setGeometry(QtCore.QRect(20, 50, 22, 111))
        self.VolumeverticalSlider.setOrientation(QtCore.Qt.Vertical)
        self.VolumeverticalSlider.setObjectName("VolumeverticalSlider")
        self.Instrument1verticalSlider = QtWidgets.QSlider(self.SettingsgroupBox)
        self.Instrument1verticalSlider.setGeometry(QtCore.QRect(90, 50, 22, 111))
        self.Instrument1verticalSlider.setOrientation(QtCore.Qt.Vertical)
        self.Instrument1verticalSlider.setObjectName("Instrument1verticalSlider")
        self.Instrument2verticalSlider = QtWidgets.QSlider(self.SettingsgroupBox)
        self.Instrument2verticalSlider.setGeometry(QtCore.QRect(170, 50, 22, 111))
        self.Instrument2verticalSlider.setOrientation(QtCore.Qt.Vertical)
        self.Instrument2verticalSlider.setObjectName("Instrument2verticalSlider")
        self.Instrument3verticalSlider = QtWidgets.QSlider(self.SettingsgroupBox)
        self.Instrument3verticalSlider.setGeometry(QtCore.QRect(260, 50, 22, 111))
        self.Instrument3verticalSlider.setOrientation(QtCore.Qt.Vertical)
        self.Instrument3verticalSlider.setObjectName("Instrument3verticalSlider")
        self.Instrument1label = QtWidgets.QLabel(self.SettingsgroupBox)
        self.Instrument1label.setGeometry(QtCore.QRect(60, 20, 101, 21))
        self.Instrument1label.setObjectName("Instrument1label")
        self.Instrument2label = QtWidgets.QLabel(self.SettingsgroupBox)
        self.Instrument2label.setGeometry(QtCore.QRect(140, 20, 81, 21))
        self.Instrument2label.setObjectName("Instrument2label")
        self.Instrument3label = QtWidgets.QLabel(self.SettingsgroupBox)
        self.Instrument3label.setGeometry(QtCore.QRect(220, 20, 81, 20))
        self.Instrument3label.setObjectName("Instrument3label")
        self.gridLayoutWidget = QtWidgets.QWidget(self.tab_3)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(40, 60, 711, 331))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.tabWidget.addTab(self.tab_4, "")
        self.gridLayout_2.addWidget(self.tabWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1660, 18))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.BrowsepushButton.setText(_translate("MainWindow", "Browse"))
        self.SettingsgroupBox.setTitle(_translate("MainWindow", "Settings "))
        self.Volumelabel.setText(_translate("MainWindow", "Volume"))
        self.PlayPausepushButton.setText(_translate("MainWindow", "Play/Pause"))
        self.ShowSpectrogrampushButton.setText(_translate("MainWindow", "Show Spectrogram"))
        self.Instrument1label.setText(_translate("MainWindow", "Instrument 1"))
        self.Instrument2label.setText(_translate("MainWindow", "Instrument 2"))
        self.Instrument3label.setText(_translate("MainWindow", "Instrument 3"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Play Tab"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "Composing Tab"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
